server:
  port: 8100

spring:
  application:
    name: eureka
  security:
    user:
      name: root
      password: root

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://root:root@${eureka.instance.hostname}:${server.port}/eureka/