server:
  port: 8200
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://root:root@${eureka.instance.hostname}:8100/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug